spring:
  application:
    name: Neuro_Bank

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:neuro_bank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/public.pem

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:8000}


app:
  jwt:
    private-key-location: classpath:certs/private.pem
    access-token-expiry: 900 #15p
    refresh-token-expiry: 604800
    issuer: banking-app
    cookie:
      domain: ${COOKIE_DOMAIN}
      secure: ${COOKIE_SECURE}