spring:
  application:
    name: Neuro_Bank

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:blur.socialnetwork@gmail.com}
    password: ${MAIL_PASSWORD:andb wbaq ndls fadn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        connection-timeout: 5000
        timeout: 5000
        write-timeout: 5000
  main:
    banner-mode: off
    lazy-initialization: true
    log-startup-info: false

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/public.pem

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2s
      connect-timeout: 2s

server:
  port: ${SERVER_PORT}

app:
  jwt:
    private-key-location: classpath:certs/private.pem
    access-token-expiry: 900
    refresh-token-expiry: 604800
    issuer: banking-app
    cookie:
      domain: ${COOKIE_DOMAIN}
      secure: ${COOKIE_SECURE}
  mail:
    from: noreply@neurobank.com
    from-name: Neuro Bank
    base-url: http://localhost:3000
  transaction:
    hash:
      secret: ${TXN_HASH_SECRET}
    iempotency:
      ttl_seconds: ${TXN_IDEMPOTENCY_TTL_SECOND}
    lock:
      account-lock-seconds: ${TXN_ACCOUNT_LOCK_SECONDS}
    rate-limit:
      create-per-minute-user: ${TXN_RATE_CREATE_USER_PER_MINUTE}
      create-per-minute-ip: ${TXN_RATE_IP_PER_MINUTE}
      reverse-per-10m-user: ${TXN_RATE_REVERSE_USER_PER_10M}
    outbox:
      dispatch-delay-minutes: ${TXN_OUTBOX_DISPATCH_DELAY_MS}
    fraud:
      high-amount-thresold: ${TXN_FRAUD_HIGH_AMOUNT_THRESHOLD}
      velocity-window-minutes: ${TXN_FRAUD_VELOCITY_WINDOW_MINUTES}
      velocity-txn-count-threshold: ${TXN_FRAUD_VELOCITY_COUNT_THRESHOLD}
      velocity-block-amount-threshold: ${TXN_FRAUD_VELOCITY_BLOCK_AMOUNT_THRESHOLD}

